language: node_js
node_js: stable
cache: yarn
script:
  - yarn test
  - yarn build
deploy:
  provider: pages
  target-branch: master
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  verbose: true
  on:
    branch: develop
